server:
  port: 8081

spring:
  application:
    name: display

hystrix:
  command:
    ProductInfo: # commandKey 이름 주의 'default'는 글로벌 설정임
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      circuitBreaker:
        requestVolumeThreshold: 1 # default: 20
        errorThresholdPercentage: 50 # default: 50
    FeignProductRemoteService#getProductInfo(String): # 함수명과 인자를 적어줌
      execute:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      circuitBreaker:
        requestVolumeThreshold: 1
        errorThresholdPercentage: 50

product:
  ribbon:
    # listOfServers: localhost:8082, localhost:7777
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka


feign:
  hystrix:
    enabled: true